import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./lib/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        brand: {
          green: "#1A3C34",
          "green-dark": "#01261f",
          "green-light": "#43655c",
          sand: "#EAE3D2",
          "sand-light": "#f1fcf7",
          "sand-dark": "#D8CEB8",
          terracotta: "#C86D51",
          "terracotta-dark": "#63200a",
          "terracotta-light": "#e68568",
        },
        "surface-tint": "#43655c",
        "primary-container": "#1a3c34",
        "secondary-container": "#eae3d2",
        "on-tertiary-fixed": "#3a0a00",
        "on-secondary-fixed": "#1e1c11",
        "on-background": "#141e1b",
        "surface-variant": "#dae5e0",
        "on-primary-container": "#83a69c",
        primary: "#01261f",
        "on-error": "#ffffff",
        "outline-variant": "#c1c8c4",
        background: "#f1fcf7",
        "surface-container-low": "#ebf6f1",
        "secondary-fixed": "#eae3d2",
        "surface-container-high": "#dfebe5",
        "on-secondary-container": "#696457",
        "on-primary": "#ffffff",
        "on-surface-variant": "#414846",
        "surface-bright": "#f1fcf7",
        "surface-container-lowest": "#ffffff",
        "tertiary-fixed": "#ffdbd0",
        "inverse-on-surface": "#e8f3ee",
        "surface-container": "#e5f0eb",
        "tertiary-container": "#63200a",
        "on-secondary-fixed-variant": "#4a473a",
        "surface-container-highest": "#dae5e0",
        "tertiary-fixed-dim": "#ffb59f",
        "primary-fixed": "#c5eadf",
        "on-tertiary": "#ffffff",
        "inverse-primary": "#aacec3",
        "inverse-surface": "#28332f",
        "on-error-container": "#93000a",
        "primary-fixed-dim": "#aacec3",
        "surface-dim": "#d1ddd7",
        error: "#ba1a1a",
        "on-primary-fixed-variant": "#2b4d44",
        secondary: "#625e51",
        tertiary: "#440d00",
        "on-primary-fixed": "#00201a",
        "on-tertiary-fixed-variant": "#793019",
        "on-secondary": "#ffffff",
        "secondary-fixed-dim": "#ccc6b6",
        "error-container": "#ffdad6",
        outline: "#717976",
        "on-tertiary-container": "#e68568",
        surface: "#f1fcf7",
        "on-surface": "#141e1b",
        sand: "#EAE3D2",
        terracotta: "#C86D51",
      },
      spacing: {
        "space-xs": "0.25rem",
        "space-sm": "0.5rem",
        "space-md": "1rem",
        "space-lg": "1.5rem",
        "space-xl": "2.5rem",
        margin: "2rem",
        gutter: "1.5rem",
      },
      fontFamily: {
        sans: ["var(--font-inter)", "system-ui", "sans-serif"],
        serif: ["var(--font-outfit)", "system-ui", "sans-serif"],
        "body-lg": ["var(--font-inter)", "sans-serif"],
        "body-md": ["var(--font-inter)", "sans-serif"],
        "body-sm": ["var(--font-inter)", "sans-serif"],
        "label-lg": ["var(--font-inter)", "sans-serif"],
        "label-md": ["var(--font-inter)", "sans-serif"],
        "label-sm": ["var(--font-inter)", "sans-serif"],
        "headline-lg": ["var(--font-outfit)", "sans-serif"],
        "headline-lg-mobile": ["var(--font-outfit)", "sans-serif"],
        "headline-md": ["var(--font-outfit)", "sans-serif"],
        "headline-sm": ["var(--font-outfit)", "sans-serif"],
        "title-lg": ["var(--font-outfit)", "sans-serif"],
        "display-lg": ["var(--font-outfit)", "sans-serif"],
        "display-lg-mobile": ["var(--font-outfit)", "sans-serif"],
      },
      fontSize: {
        "body-lg": ["16px", { lineHeight: "24px", letterSpacing: "0em", fontWeight: "400" }],
        "body-md": ["14px", { lineHeight: "20px", letterSpacing: "0.01em", fontWeight: "400" }],
        "label-lg": ["14px", { lineHeight: "20px", letterSpacing: "0.02em", fontWeight: "600" }],
        "headline-lg": ["40px", { lineHeight: "48px", letterSpacing: "-0.015em", fontWeight: "500" }],
        "title-lg": ["18px", { lineHeight: "24px", letterSpacing: "0.005em", fontWeight: "600" }],
        "label-sm": ["10px", { lineHeight: "14px", letterSpacing: "0.06em", fontWeight: "600" }],
        "headline-lg-mobile": ["28px", { lineHeight: "34px", letterSpacing: "-0.01em", fontWeight: "500" }],
        "label-md": ["12px", { lineHeight: "16px", letterSpacing: "0.03em", fontWeight: "500" }],
        "display-lg": ["56px", { lineHeight: "64px", letterSpacing: "-0.02em", fontWeight: "600" }],
        "headline-md": ["28px", { lineHeight: "36px", letterSpacing: "-0.01em", fontWeight: "500" }],
        "display-lg-mobile": ["38px", { lineHeight: "44px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "body-sm": ["12px", { lineHeight: "18px", letterSpacing: "0.015em", fontWeight: "400" }],
        "headline-sm": ["22px", { lineHeight: "28px", letterSpacing: "0em", fontWeight: "600" }],
      },
      boxShadow: {
        luxury: "0 20px 50px -12px rgba(26, 60, 52, 0.12)",
        card: "0 2px 8px -2px rgba(20, 30, 27, 0.04), 0 1px 3px 0 rgba(74, 69, 62, 0.06)",
      },
    },
  },
  plugins: [],
};

export default config;
