"use client";

import React from "react";
import {
  Home,
  Wrench,
  Building2,
  CreditCard,
  KeyRound,
  AlertTriangle,
  User,
  ShieldCheck,
  CheckCircle2,
  Sparkles,
  Droplets,
  Trees,
  Shirt,
  Hammer,
  Paintbrush,
  Hotel,
  Compass,
  Lock,
  ChevronRight,
  ChevronDown,
  Headset,
  View,
  Zap,
  Leaf,
  ArrowRight,
  MapPin,
  Globe,
  Cookie,
  HardHat,
  Phone,
  MessageCircle,
  Activity,
  RefreshCw,
  Waves,
  Check,
  Sun,
  Users,
  MoveHorizontal,
  Camera,
  Calendar,
  CalendarCheck,
  Shield,
} from "lucide-react";

const iconMap: Record<string, React.ElementType> = {
  villa: Home,
  home_repair_service: Wrench,
  domain: Building2,
  apartment: Building2,
  payments: CreditCard,
  vpn_key: KeyRound,
  emergency: AlertTriangle,
  person: User,
  verified: ShieldCheck,
  verified_user: ShieldCheck,
  check_circle: CheckCircle2,
  water_lux: Droplets,
  pool: Waves,
  potted_plant: Trees,
  cleaning_services: Sparkles,
  iron: Shirt,
  carpenter: Hammer,
  format_paint: Paintbrush,
  hotel: Hotel,
  hotel_class: Hotel,
  architecture: Compass,
  lock_reset: Lock,
  lock: Lock,
  chevron_right: ChevronRight,
  expand_more: ChevronDown,
  support_agent: Headset,
  "360": View,
  bolt: Zap,
  eco: Leaf,
  arrow_forward: ArrowRight,
  location_on: MapPin,
  pin_drop: MapPin,
  travel_explore: Globe,
  cookie: Cookie,
  engineering: HardHat,
  call: Phone,
  chat: MessageCircle,
  sensors: Activity,
  sync: RefreshCw,
  check: Check,
  solar_power: Sun,
  group: Users,
  drag_indicator: MoveHorizontal,
  photo_camera: Camera,
  calendar_month: Calendar,
  event_repeat: CalendarCheck,
  shield: Shield,
};

export default function AppIcon({
  name,
  className = "w-5 h-5",
}: {
  name: string;
  className?: string;
}) {
  const IconComponent = iconMap[name] || ShieldCheck;
  return <IconComponent className={`shrink-0 ${className}`} aria-hidden="true" />;
}
